Make Speaker description width 100% for 992px to 1200px screen
fossasia/open-event-wsgen pull request #2353
Opened 2020-10-01 20:43 UTC by dsnehasish74

Previously it was of width 50% by default ............ according to this issue I made it 100%.

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [ ] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

#### Changes proposed in this pull request:

-
-
-

Fixes #2322

2020-10-02 06:08 UTC, digitalPlayer1125 reviewed
This seems fine. 
Maybe add padding-top as well so that the author name doesn't stick to the image?

2020-10-02 19:51 UTC, digitalPlayer1125 requested changes
Just a change, I think having padding-top as 20px would be better than 40px, as 40px is more of overuse of whitespace. Compare the two screenshots as attached. Makes sense?
![image](https://user-images.githubusercontent.com/46300090/94963549-ee931200-0515-11eb-95d6-4af86822146b.png)
![image](https://user-images.githubusercontent.com/46300090/94963572-fd79c480-0515-11eb-9b55-7dbf4a738a11.png)

2020-10-02 20:07 UTC, digitalPlayer1125 approved these changes
Great!

2020-10-12 15:00 UTC, Raunaksingh100 reviewed
Plz fixed your travis cl failed ........

2020-10-12 15:26 UTC, digitalPlayer1125 commented
@Raunaksingh100 As you can see that it is just a change in CSS, the travis CI error has nothing to do with it [It is caused due to Selenium Timeout]

2020-10-12 15:38 UTC, Raunaksingh100 commented on src/backend/_scss/application.scss
> +      padding-top:40px;
> Colon after property should be followed by one space

@digital read this

2020-10-12 15:45 UTC, digitalPlayer1125 commented on src/backend/_scss/application.scss
> +      padding-top:40px;
This has been already resolved.

2020-10-13 14:42 UTC, iamareebjamal approved these changes

2020-10-13 14:42 UTC, merged